name: BordSmpPlugin
main: slard.craft.BordSmpPlugin
version: 1.0
api-version: 1.18
commands:
  inborder:
    description: Informs player whether they are within the border or not
    usage: /<command>